/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("org.springframework.boot") version "3.2.5"
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":infrastructure"))
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.2.5"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    runtimeOnly("com.h2database:h2")
}

application {
    mainClass = "com.it.exalt.belair.application.BelairBuvetteApplication"
}
